//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPC.BD_MyPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public int ID { get; set; }
        public Nullable<int> ID_Problem { get; set; }
        public Nullable<int> ID_Repair { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual Repair Repair { get; set; }
    }
}
